disableKinds = ["taxonomy","taxonomyTerm"]

baseURL = 'https://release.digdir.no'
languageCode = 'nb'
title = 'Release notes'

timeZone = "Europe/Oslo"

defaultContentLanguage = 'no'

sectionPagesMenu = 'main'
pluralizelisttitles = false

theme = 'digdir-hugo-theme'

[outputFormats]
[outputFormats.JSON]
mediatype = "application/json"
baseName = "index"
isPlainText = true

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark]
      [markup.goldmark.extensions]     
        linkify = false

[params]
  logo = "/images/digdir_positiv.png"