name: Build hugo site

on:
  push:
    branches: [ main ]
    paths-ignore:
      - ".github/**"
      - ".README"
  workflow_run:
    workflows: ["Update release notes"]
    types:
      - completed

jobs:
  build-site:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
        with:
          submodules: true
          fetch-depth: 1

      # install dependencies in hugo-theme
      - run: npm install

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@16361eb4acea8698b220b76c0d4e84e1fd22c61d # 2.6.0
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build with Hugo
        run: hugo --environment production -F --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # 4.0.0
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
